version: '3.9'

services:
  simple-auction:
    build:
      context: .
    volumes:
      - .env:/app/.env:ro
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: mysql://auction-user:auction-password@mysql:3306/auction-db
      NODE_ENV: production
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.3
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: auction-db
      MYSQL_USER: auction-user
      MYSQL_PASSWORD: auction-password
      MYSQL_ROOT_PASSWORD: db-root-password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s